osx_image: xcode11.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods
 - pod install --repo-update --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Logsene.xcworkspace -scheme Logsene-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
