osx_image: xcode8.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
 - gem install cocoapods
 - pod install --repo-update --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Logsene.xcworkspace -scheme Logsene-Example -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
